=== japamat/bumpr/backend/schemas/userNew.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "username",
    "password",
    "email"
  ],
  "properties": {
    "username": {
      "$id": "#/properties/username",
      "type": "string",
      "title": "The Username Schema",
      "default": "",
      "examples": [
        "japamat"
      ],
      "pattern": "^(.*)$"
    },
    "password": {
      "$id": "#/properties/password",
      "type": "string",
      "title": "The Password Schema",
      "default": "",
      "examples": [
        "password"
      ],
      "pattern": "^(.*)$"
    },
    "image_url": {
      "$id": "#/properties/image_url",
      "type": "string",
      "title": "The Image_url Schema",
      "default": "",
      "examples": [
        "https://cdn5.vectorstock.com/i/thumb-large/66/14/default-avatar-photo-placeholder-profile-picture-vector-21806614.jpg"
      ],
      "pattern": "^(.*)$"
    },
    "bio": {
      "$id": "#/properties/bio",
      "type": "string",
      "title": "The Bio Schema",
      "default": "",
      "examples": [
        "my name is Jason, I built this thing!"
      ],
      "pattern": "^(.*)$"
    },
    "email": {
      "$id": "#/properties/email",
      "type": "string",
      "title": "The Email Schema",
      "default": "",
      "examples": [
        "jpmatthias90@gmail.com"
      ],
      "pattern": "^(.*)$"
    },
    "header_image_url": {
      "$id": "#/properties/header_image_url",
      "type": "string",
      "title": "The Header_image_url Schema",
      "default": "",
      "examples": [
        "https://cdn5.vectorstock.com/i/thumb-large/66/14/default-avatar-photo-placeholder-profile-picture-vector-21806614.jpg"
      ],
      "pattern": "^(.*)$"
    },
    "location": {
      "$id": "#/properties/location",
      "type": "string",
      "title": "The Location Schema",
      "default": "",
      "examples": [
        "San Francisco, CA"
      ],
      "pattern": "^(.*)$"
    }
  }
}

=== japamat/bumpr/backend/seedData/users.json
[
  {
    "email": "ronald38@yahoo.com",
    "username": "tuckerdiane",
    "image_url": "https://randomuser.me/api/portraits/men/80.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Movement later fund employee site turn.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mo2x3aAnRH1st5lhmo1_1280.jpg",
    "location": "Garrettburgh"
  },
  {
    "email": "richard65@martin.net",
    "username": "edward88",
    "image_url": "https://randomuser.me/api/portraits/lego/5.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Decision professional real each citizen level.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mo2xijE2nr1st5lhmo1_1280.jpg",
    "location": "South Aprilmouth"
  },
  {
    "email": "helen38@hotmail.com",
    "username": "joanna15",
    "image_url": "https://randomuser.me/api/portraits/women/6.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Maybe key community young ahead.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh17lfd9R1st5lhmo1_1280.jpg",
    "location": "South Kellymouth"
  },
  {
    "email": "mcdonaldjohn@parks-miller.com",
    "username": "kwilliams",
    "image_url": "https://randomuser.me/api/portraits/lego/3.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Hotel together show gas seven.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mp6rzyNlAN1st5lhmo1_1280.jpg",
    "location": "New Harry"
  },
  {
    "email": "ljohnson@grimes-stevens.net",
    "username": "palmermichael",
    "image_url": "https://randomuser.me/api/portraits/women/97.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Cell itself institution couple should.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mo1h6tGOZf1st5lhmo1_1280.jpg",
    "location": "New Candiceburgh"
  },
  {
    "email": "angelicaparker@nguyen.com",
    "username": "becklinda",
    "image_url": "https://randomuser.me/api/portraits/lego/5.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Concern phone sport whatever professor material.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh1d7s3UD1st5lhmo1_1280.jpg",
    "location": "Jessicaton"
  },
  {
    "email": "laura85@barrett-hunter.com",
    "username": "pattersonangela",
    "image_url": "https://randomuser.me/api/portraits/men/50.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Experience at Republican party large option project.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh2m1hnS81st5lhmo1_1280.jpg",
    "location": "Heatherside"
  },
  {
    "email": "murphyjohn@hernandez-beard.info",
    "username": "crawfordshawn",
    "image_url": "https://randomuser.me/api/portraits/men/17.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Resource source beyond beautiful product add mention.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mpp6f50W261st5lhmo1_1280.jpg",
    "location": "Lake Lindaburgh"
  },
  {
    "email": "bgray@hotmail.com",
    "username": "psampson",
    "image_url": "https://randomuser.me/api/portraits/men/74.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Figure seat everybody agency.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mp6s32zb6l1st5lhmo1_1280.jpg",
    "location": "Robertsstad"
  },
  {
    "email": "tatemallory@sanford-armstrong.com",
    "username": "wrightgeorge",
    "image_url": "https://randomuser.me/api/portraits/women/52.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Often beyond enough why.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mo2xijE2nr1st5lhmo1_1280.jpg",
    "location": "East Michellemouth"
  },
  {
    "email": "lauraconner@hotmail.com",
    "username": "webbmark",
    "image_url": "https://randomuser.me/api/portraits/women/7.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Spring language his several drop.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mp6scv2xrZ1st5lhmo1_1280.jpg",
    "location": "Rhondafort"
  },
  {
    "email": "bookerricky@gmail.com",
    "username": "veronicahaynes",
    "image_url": "https://randomuser.me/api/portraits/women/61.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Term left view.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mo2xgqdEFn1st5lhmo1_1280.jpg",
    "location": "Port William"
  },
  {
    "email": "murphytimothy@yahoo.com",
    "username": "stacymartin",
    "image_url": "https://randomuser.me/api/portraits/men/44.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Arrive indicate finally.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh0uemhCk1st5lhmo1_1280.jpg",
    "location": "Wandaberg"
  },
  {
    "email": "timothyritter@gmail.com",
    "username": "mendozabrian",
    "image_url": "https://randomuser.me/api/portraits/men/56.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Result team myself western past movie enough.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mp6scv2xrZ1st5lhmo1_1280.jpg",
    "location": "Petersberg"
  },
  {
    "email": "christophersims@castaneda-soto.com",
    "username": "wjefferson",
    "image_url": "https://randomuser.me/api/portraits/men/12.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Start decision go lay.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh25vNOvI1st5lhmo1_1280.jpg",
    "location": "North Katherinechester"
  },
  {
    "email": "gcherry@mclaughlin.com",
    "username": "kingdonna",
    "image_url": "https://randomuser.me/api/portraits/women/31.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "View beat service history field.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh29fxz111st5lhmo1_1280.jpg",
    "location": "Lake Roberttown"
  },
  {
    "email": "brian35@lopez.com",
    "username": "andersontroy",
    "image_url": "https://randomuser.me/api/portraits/men/58.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Ever late future.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mp6scv2xrZ1st5lhmo1_1280.jpg",
    "location": "Chenstad"
  },
  {
    "email": "terrydestiny@ramos.net",
    "username": "zwilkins",
    "image_url": "https://randomuser.me/api/portraits/women/34.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Role letter site chair pretty coach.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh1uhYnog1st5lhmo1_1280.jpg",
    "location": "East Charlesberg"
  },
  {
    "email": "scottlori@hotmail.com",
    "username": "ashley13",
    "image_url": "https://randomuser.me/api/portraits/men/48.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Form nearly win hit tend society agree.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh25vNOvI1st5lhmo1_1280.jpg",
    "location": "West Travisfort"
  },
  {
    "email": "hjones@murphy-jacobs.net",
    "username": "tiffanywilson",
    "image_url": "https://randomuser.me/api/portraits/lego/6.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Region citizen pressure trip.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh1jdFvHR1st5lhmo1_1280.jpg",
    "location": "New Jared"
  },
  {
    "email": "lthomas@gmail.com",
    "username": "qsmith",
    "image_url": "https://randomuser.me/api/portraits/men/41.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Company space end.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh25vNOvI1st5lhmo1_1280.jpg",
    "location": "Joseburgh"
  },
  {
    "email": "larsondavid@yahoo.com",
    "username": "sanchezangela",
    "image_url": "https://randomuser.me/api/portraits/men/39.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Country cover commercial billion.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mopq4kHmAg1st5lhmo1_1280.jpg",
    "location": "Hamiltonbury"
  },
  {
    "email": "karen78@miller-tyler.com",
    "username": "liulauren",
    "image_url": "https://randomuser.me/api/portraits/men/90.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Wall yes between main.",
    "header_image_url": "https://splashbase.s3.amazonaws.com/unsplash/regular/tumblr_mnh25vNOvI1st5lhmo1_1280.jpg",
    "location": "Cardenasburgh"
  },
  {
    "email": "zbowman@hotmail.com",
    "username": "omartinez",
    "image_url": "https://randomuser.me/api/portraits/women/12.jpg",
    "password": "$2b$12$Q1PUFjhN/AWRQ21LbGYvjeLpZZB6lfZ1BPwifHALGO6oIbyC3CmJe",
    "bio": "Street human expert culture.",
